# Generated by Django 4.1.3 on 2022-11-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_number', models.IntegerField()),
                ('to_number', models.IntegerField()),
                ('result_list', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceRandomGenerator',
            fields=[
                ('randomgenerator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.randomgenerator')),
            ],
            bases=('polls.randomgenerator',),
        ),
    ]
