# Generated by Django 4.1.3 on 2022-11-21 15:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_randomgenerator_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomgenerator',
            name='generator_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('advanced', 'Advanced')], default='normal', max_length=50),
        ),
        migrations.DeleteModel(
            name='AdvanceRandomGenerator',
        ),
        migrations.CreateModel(
            name='AdvanceRandomGenerator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.randomgenerator',),
            managers=[
                ('advance_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
